### PR TITLE
Display tooltip with full citation using react-tooltip

### LINKED ISSUE #6: Cite/reflist enhancements
- [x] smooth scroll
- [x] highlight reflist item
- [ ] tooltip on hover?

### PR DESCRIPTION
**Pull request by miluoshi**
fixes #6

### CODE REVIEW

**Comment by rosslh** [comment]
It looks like you didn't add the tooltip package to `package.json`. Please run `npm i react-tooltip` and commit the results :slightly_smiling_face:

**Comment by miluoshi** [comment]
Oh sorry, forgot to add it. Will do 🙂

**Comment by rosslh** [comment]
Awesome stuff. I am having an issue where the first two citations don't have a tooltip displaying. Are you able to reproduce this issue?

Also can you change the tooltip `type` attribute to "light"? I just think it looks a little nicer

**Comment by miluoshi** [comment]
I tried "light" color, but it had a terrible readability. "dark" looks much better. 

The problem with first 2 tooltips persists on deployed instance, but I can't reproduce it locally... strange.

**Pull request closed without merging**
