### PR TITLE
Fix Prettier + ESLint setup

### PR DESCRIPTION
**Pull request by miluoshi**
While I tried to fix another issue I found out your ESLint + Prettier setup is not working correctly, so I was not able to commit with the precommit hook on. 

I fixed the following:
- Added eslint-plugin-prettier as `prettier` entry into eslint's `plugins` field
- Added prettier configs to `extends` field to turn off formatting rules of other configs conflicting with the Prettier. Now only Prettier deals with the formatting.
- Changed some `react` rules from error to warning - only for rules which eslint can't automatically fix
- Removed `artifacts` directory and added it to .gitignore file as it is a build artifact which gets created after each build and should not be commited to a git repo
- Updated package.json to use eslint to run prettier and removed the unused script. Updated readme to use "format" script instead of removed "prettier" one
- Run `npm run format` script to format files according to the ESLint/Prettier rules

### CODE REVIEW

**Comment by eostrom** [comment]
1. Thank you for doing this, I've been running into the same problems.
2. I've been using `yarn` on this project, and it looks like you're using `npm`. That means you checked in a change to `package.json` and the resulting change to `package-lock.json`, but no change to `yarn.lock`. When I ran `yarn install` on this branch, it created a new change to `yarn.lock`, which isn't part of the change I'm trying to make.

I think the project (i.e., @rosslh) should choose one or the other, document that choice in the `README`, and delete `package-lock.json` (if we're using `yarn`) or `yarn.lock` (if we're using `npm`).

(I'd be happy to submit that PR, I just don't feel authorized to make the decision.)

**Comment by eostrom** [comment]
Never mind, I see `npm` is already mentioned in the `README`. I'll submit a PR to jettison the misleading `yarn.lock` file.

**Comment by miluoshi** [comment]
I also prefer to use Yarn, but I saw npm being used in `README.md` and  the `package-lock.json` file present in the repo so I used npm. Now I see there is `yarn.lock` too.

I can commit changes to `yarn.lock` too and then @rosslh can decide which package manager to choose for this project.

**Comment by rosslh** [comment]
@miluoshi @eostrom This project uses npm. I'll make a PR to remove the yarn.lock file; sorry for the confusion

**Pull request merged**
